# Generated by Django 4.0.1 on 2022-06-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('titulo', models.CharField(default='--', max_length=80, primary_key=True, serialize=False)),
                ('subtitulo', models.CharField(default='--', max_length=80)),
                ('historia', models.CharField(default='--', max_length=1000)),
                ('ubicacion', models.CharField(default='--', max_length=80)),
                ('imagen', models.ImageField(default='Falta_imagen.jpg', null=True, upload_to='fotos')),
                ('publicar', models.BooleanField(default=False)),
                ('usuario', models.CharField(default='--', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_CaosNew.noticia')),
            ],
        ),
    ]
