# Generated by Django 4.0.4 on 2022-06-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_CaosNew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='nombre',
            field=models.ForeignKey(default='--', on_delete=django.db.models.deletion.CASCADE, to='Web_CaosNew.categoria'),
        ),
    ]
