# Generated by Django 4.0.4 on 2022-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_CaosNew', '0002_noticia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default='--'),
        ),
    ]
