# Generated by Django 4.0.4 on 2022-06-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_CaosNew', '0004_alter_noticia_historia_alter_noticia_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default='--', max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default='--', max_length=300, primary_key=True, serialize=False),
        ),
    ]
