# Generated by Django 4.0.5 on 2022-06-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_CaosNew', '0006_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contador', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(default='--', max_length=300)),
                ('nombre', models.CharField(default='--', max_length=300)),
                ('correo', models.CharField(default='--', max_length=300)),
                ('telefono', models.CharField(default='--', max_length=300)),
                ('region', models.CharField(default='--', max_length=300)),
                ('ciudad', models.CharField(default='--', max_length=300)),
                ('termino', models.BooleanField(default=False)),
            ],
        ),
    ]
